### ISSUE TITLE
add app.js and package.json so a dev box can be run locally and easily.

### ISSUE THREAD

**Issue by DrewMcArthur** [AnotherIndieDevStudio/Coopgamemaking-01#1]
I'll add a simple app.js and package file so that the game can be run easily on a linux box, for local testing purposes.  I'll also add instructions to the readme (or wiki?) about how to get it quickly set up on a local box, it'll be a few lines of code in a terminal, easy.  

I've forked the repo, and have begun working on adding these features.

**Comment by AnotherIndieDevStudio** [comment]
This has been added.
