### ISSUE TITLE
savegame.php XSS

### ISSUE THREAD

**Issue by JhonnyAl** [AnotherIndieDevStudio/Coopgamemaking-01#7]
HTML code can be injected in the parameters:

http://coopgamemaking.com/savegame.php?id=%3Ch1%20style=%22font-size:30em;color:rgb(255,0,0);%22%3EHello%3C/h1%3E

**Comment by joshgit** [comment]
How does this help?

**Comment by AnotherIndieDevStudio** [comment]
Adding prepared statements to php files as soon as possible.

**Comment by DrewMcArthur** [comment]
@joshgit it doesn't help, this isn't a good thing.  The ability to inject code means that a user could potentially write code that gained them access to the server, to do malicious things.  In the case of the link provided, all it does is show a big "HELLO", but there are more possibilities.  Prepared statements in the php file will prevent this from happening.

**Comment by joshgit** [comment]
Ok, wasn't sure what your point was, or whoever made the original post.

```
  From: Drew McArthur <notifications@github.com>
```

 To: AnotherIndieDevStudio/Coopgamemaking-01 Coopgamemaking-01@noreply.github.com 
Cc: joshgit oopjosh@yahoo.com 
 Sent: Thursday, May 7, 2015 1:17 PM
 Subject: Re: [Coopgamemaking-01] savegame.php XSS (#7)

@joshgit it doesn't help, this isn't a good thing. The ability to inject code means that a user could potentially write code that gained them access to the server, to do malicious things. In the case of the link provided, all it does is show a big "HELLO", but there are more possibilities. Prepared statements in the php file will prevent this from happening. —

**Comment by AnotherIndieDevStudio** [comment]
This has been fixed. Thank you for bringing this to my attention.
